# Generated by Django 4.1.1 on 2022-10-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_copy_id_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='id_quantity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.quantity'),
        ),
    ]
