# Generated by Django 4.1.1 on 2022-10-26 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_remove_copy_id_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='balance',
            field=models.IntegerField(default=200000),
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_card', models.CharField(choices=[('Tarjeta de Débito', 'Tarjeta de Débito'), ('Tarjeta de Crédito', 'Tarjeta de Crédito')], max_length=200)),
                ('number_card', models.IntegerField()),
                ('cvv', models.IntegerField()),
                ('cardholder', models.CharField(max_length=200)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
            ],
        ),
    ]
