# Generated by Django 4.1.1 on 2022-10-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_paymentmethod_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
    ]
