# Generated by Django 4.1.1 on 2022-10-30 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_paymentmethod_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentmethod',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
