# Generated by Django 4.1.1 on 2022-11-01 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_paymentmethod_expiration_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paymentmethod',
            old_name='owner',
            new_name='customer',
        ),
    ]
