# Generated by Django 4.1.1 on 2022-11-05 20:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100000000000), django.core.validators.MinValueValidator(100000)]),
        ),
    ]
