# Generated by Django 4.1.1 on 2022-11-05 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_customer_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='dni',
            field=models.IntegerField(null=True),
        ),
    ]
