# Generated by Django 4.1.1 on 2022-11-05 23:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_customer_cellphone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='cellphone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message='Please enter a valid phone number.', regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Please enter a valid name', regex='/^[a-zA-Z]+$/')]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='surname',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Please enter a valid surname', regex='/^[a-zA-Z]+$/')]),
        ),
    ]
