# Generated by Django 4.1.1 on 2022-11-06 15:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_alter_customer_name_alter_customer_surname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Please enter a valid name for the cardholder.', regex='[a-zA-Z_.-]+$')]),
        ),
        migrations.AlterField(
            model_name='paymentmethod',
            name='number_card',
            field=models.IntegerField(),
        ),
    ]
