# Generated by Django 4.1.1 on 2022-11-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_paymentmethod_cardholder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder',
            field=models.CharField(max_length=200),
        ),
    ]
