# Generated by Django 4.1.1 on 2022-11-06 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_paymentmethod_cardholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='cardholder',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Please enter a valid name for the cardholder.', regex='[a-zA-Z_.-]+$')]),
        ),
    ]
