# Generated by Django 4.1.1 on 2022-11-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_remove_branchoffice_department_branchoffice_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branchoffice',
            name='country',
        ),
        migrations.RemoveField(
            model_name='branchoffice',
            name='region',
        ),
        migrations.AddField(
            model_name='branchoffice',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='branchoffice',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
