# Generated by Django 4.1.1 on 2022-11-09 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_branchoffice_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='copy',
            name='is_used',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='quantity',
            name='is_used',
            field=models.BooleanField(null=True),
        ),
    ]
