# Generated by Django 4.1.1 on 2022-11-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_copy_is_used_quantity_is_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='literary_gender',
            field=models.CharField(choices=[('Universal Literary', 'Universal Literary'), ('General', 'General'), ('Suspenso y Terror', 'Suspenso y Terror'), ('Historica', 'Historica'), ('Romantica', 'Romantica'), ('Fantasia y Ciencia Ficción', 'Fantasia y Ciencia Ficción')], max_length=200),
        ),
        migrations.AlterField(
            model_name='copy',
            name='state',
            field=models.CharField(choices=[('D', 'Disponible'), ('A', 'Agotado'), ('R', 'Reservado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='customer',
            name='literary_prefer',
            field=models.CharField(blank=True, choices=[('Universal Literary', 'Universal Literary'), ('General', 'General'), ('Suspenso y Terror', 'Suspenso y Terror'), ('Historica', 'Historica'), ('Romantica', 'Romantica'), ('Fantasia y Ciencia Ficción', 'Fantasia y Ciencia Ficción')], default='1', max_length=200),
        ),
    ]
