# Generated by Django 4.1.1 on 2022-11-09 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_book_literary_gender_alter_copy_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='total_quantity',
            field=models.IntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='copy',
            name='state',
            field=models.CharField(choices=[('D', 'Disponible'), ('V', 'Vendido'), ('R', 'Reservado')], max_length=10),
        ),
        migrations.AlterField(
            model_name='quantity',
            name='is_used',
            field=models.BooleanField(default=True),
        ),
    ]
