# Generated by Django 4.1.1 on 2022-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_booking_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_hour',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
