# Generated by Django 4.1.1 on 2022-11-17 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_shipping_city_shipping_country_shipping_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
