# Generated by Django 4.1.1 on 2022-11-17 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_booking_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipping',
            name='date_shipping',
            field=models.DateField(auto_now=True),
        ),
    ]
