# Generated by Django 4.1.1 on 2022-11-17 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_alter_shipping_date_shipping'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='booking_hour',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='shipping',
            name='state_shipping',
            field=models.CharField(choices=[('PREPARING', 'PREPARING'), ('SENT', 'SENT'), ('DELIVERED', 'DELIVERED')], default='PREPARING', max_length=200),
        ),
    ]
