# Generated by Django 4.1.1 on 2022-11-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0037_order_booking_hour_alter_shipping_state_shipping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='booking_hour',
        ),
    ]
